language: php
php:
  - '5.6'

services:
  - mysql

before_script:
  - mysql -e "create database IF NOT EXISTS klusbibapi_test;" -uroot;
  - composer install
  - vendor/bin/phinx migrate

# omitting "script:" will default to phpunit
script: phpunit --bootstrap tests/bootstrap.php --coverage-text
