language: php
php:
  - '7.0'

env:
  - DATABASE_URL=mysql://root:@127.0.0.1:3306/klusbibapi_test
  
services:
  - mysql

before_script:
  - mysql -e "create database IF NOT EXISTS klusbibapi_test;" -uroot;
  - composer install
  - vendor/bin/phinx migrate -e ci --verbose

# omitting "script:" will default to phpunit
script: phpunit --bootstrap tests/bootstrap.php --coverage-text
