language: php
php:
  - '7.0'

services:
  - mysql

before_script:
  - mysql -e "create database IF NOT EXISTS klusbibapi_test;" -uroot;
  - composer install
  - vendor/bin/phinx migrate -e ci

# omitting "script:" will default to phpunit
script: phpunit --bootstrap tests/bootstrap.php --coverage-text
