language: php
php:
  - '7.0'

env:
  - TEST_DATABASE_URL=mysql://root:@127.0.0.1:3306/klusbibapi JWT_SECRET=dummy

services:
  - mysql

before_script:
  - mysql -e "create database IF NOT EXISTS klusbibapi;" -uroot;
  - composer install
  - vendor/bin/phinx migrate -e ci --verbose

# omitting "script:" will default to phpunit
script: vendor/bin/phpunit --verbose --bootstrap tests/bootstrap.php --coverage-text

after_failure:
  - cat $HOME/build/renardeau/klusbibapi/tests/logs/app.log