 [
	{
		"id": "wood-1",
		"name": "wipzaag",
		"description": "Simpele wipzaag",
		"link": null,
		"category": "wood"
	},
	{
		"id": "wood-2",
		"name": "cirkelzaag",
		"description": "Makita: Model 5903R is a redesigned version of the predecessor Model 5900BR. Model 5903R is equipped with riving knife, electric brake, more powerful Makita motor, more efficient chip/sawdust ejection port, and extremely durable aluminum base. It complies with CENELEC.",
		"link": "http://www.makitauk.com/products/saws/circular-saws/all-circular-saws/5903r-235mm-circular-saw.html",
		"category": "wood",
		"img": "img/tools/cirkelzaag-makita.jpg"
	},
	{
		"id": "constr-1",
		"name": "Boormachine",
		"description": null,
		"link": null,
		"category": "construction"
	},
	{
		"id": "constr-2",
		"name": "Boorhamer",
		"description": "Enkel voor demo",
		"link": null,
		"category": "construction"
	},
	{
		"id": "electr-1",
		"name": "mutlimeter",
		"description": null,
		"link": "http://www.puky.be/nl/mod_produkte_produkt/kategorie/laufrad_lr_m/produkt/Laufrad_LR_M_rotgelb/index.html",
		"category": "electricity"
	},
	{
		"id": "electr-2",
		"name": "kniptang",
		"description": null,
		"link": null,
		"category": "electricity"
	}
]	
