name: Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the deelbaarm branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: 'master'

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@test.klusbib.be:22/api'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          
